#!/usr/bin/env python3
"""Ω-7B.1 Trust Validation Report #1 — Formal markdown report generator.

Generates:
    reports/trust_validation_report.md

Computes:
* Trust ↔ Resolution correlation
* Confidence ↔ Resolution correlation
* Top divergences
* Top drift events
* Trust distribution changes

Usage:
    python scripts/hardening/trust_validation_report.py
        [--api-url URL] [--api-key KEY]
        [--output reports/trust_validation_report.md]
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests

REPORT_HEADER = """# Trust Validation Report #1

**Date:** {date}
**Phase:** Ω-7B.1 Operational Validation
**Status:** {status}

---

## Executive Summary

{summary}

---

## 1. Trust ↔ Resolution Correlation

{trust_resolution}

## 2. Confidence ↔ Resolution Correlation

{confidence_resolution}

## 3. Trust Distribution

{trust_distribution}

## 4. Top Divergences (Confidence Rank ≠ Trust Rank)

{divergences}

## 5. Top Drift Events

{drift_events}

## 6. Raw Counts

{raw_counts}

---

## Assessment

{assessment}

---

*Generated by `scripts/hardening/trust_validation_report.py`*
"""


def _fetch(endpoint: str, api_url: str, api_key: str) -> dict:
    headers = {"Authorization": f"Bearer {api_key}"}
    url = f"{api_url}{endpoint}"
    response = requests.get(url, headers=headers, timeout=30)
    response.raise_for_status()
    return response.json()


def _corr_text(corr: Optional[float], pval: Optional[float]) -> str:
    if corr is None:
        return "*Insufficient data for correlation*\n"
    lines = [
        f"- **Spearman correlation:** {corr:.3f}",
        f"- **P-value:** {pval:.4f}" if pval is not None else "",
    ]
    if corr >= 0.5:
        lines.append("- **Assessment:** Good (>= 0.5)")
    elif corr >= 0.3:
        lines.append("- **Assessment:** Acceptable (>= 0.3)")
    elif corr >= 0.0:
        lines.append("- **Assessment:** Poor (< 0.3)")
    else:
        lines.append("- **Assessment:** Negative (inverted relationship)")
    return "\n".join(line for line in lines if line) + "\n"


def _compute_correlation(
    xs: List[float],
    ys: List[float],
) -> Dict[str, Any]:
    try:
        from scipy.stats import spearmanr  # type: ignore[import-untyped]
    except ImportError:
        return {"available": False, "note": "scipy not installed"}
    if len(xs) < 3:
        return {
            "available": True,
            "correlation": None,
            "p_value": None,
            "sample_size": len(xs),
            "note": "Need 3+ data points",
        }
    corr, pval = spearmanr(xs, ys)
    return {
        "available": True,
        "correlation": round(float(corr), 3) if corr is not None else None,
        "p_value": round(float(pval), 4) if pval is not None else None,
        "sample_size": len(xs),
    }


def _trust_resolution_section(
    trust_types: List[dict],
    effectiveness_types: List[dict],
) -> str:
    eff_map = {
        t["type"]: t.get("resolution_rate", 0.0)
        for t in effectiveness_types
        if "type" in t
    }
    trust_scores = []
    resolution_rates = []
    for t in trust_types:
        tn = t.get("type", "")
        if tn in eff_map:
            trust_scores.append(t.get("trust_score", 0.0))
            resolution_rates.append(eff_map[tn])
    result = _compute_correlation(trust_scores, resolution_rates)
    if not result.get("available"):
        return "*Correlation computation unavailable (scipy not installed)*\n"
    return _corr_text(
        result.get("correlation"), result.get("p_value")
    )


def _confidence_resolution_section(
    recommendations: List[dict],
    effectiveness_types: List[dict],
) -> str:
    eff_map = {
        t["type"]: t.get("resolution_rate", 0.0)
        for t in effectiveness_types
        if "type" in t
    }
    conf_scores = []
    resolution_rates = []
    for r in recommendations:
        rec_type = r.get("type", r.get("recommendation_type", ""))
        if rec_type in eff_map:
            conf_scores.append(r.get("confidence", 0.0))
            resolution_rates.append(eff_map[rec_type])
    result = _compute_correlation(conf_scores, resolution_rates)
    if not result.get("available"):
        return "*Correlation computation unavailable (scipy not installed)*\n"
    return _corr_text(
        result.get("correlation"), result.get("p_value")
    )


def _trust_distribution_section(trust_types: List[dict]) -> str:
    bands = {
        "highly_trusted": 0, "trusted": 0, "watch": 0,
        "weak": 0, "untrusted": 0,
    }
    for t in trust_types:
        score = t.get("trust_score", 0.0)
        if score >= 0.80:
            bands["highly_trusted"] += 1
        elif score >= 0.60:
            bands["trusted"] += 1
        elif score >= 0.40:
            bands["watch"] += 1
        elif score >= 0.20:
            bands["weak"] += 1
        else:
            bands["untrusted"] += 1
    total = sum(bands.values()) or 1
    lines = []
    for label, count in bands.items():
        pct = (count / total) * 100
        bar = "█" * int(pct / 5)
        lines.append(
            f"- **{label}:** {count} ({pct:.1f}%) {bar}"
        )
    lines.append("")
    # Health assessment
    ht = bands["highly_trusted"]
    tr = bands["trusted"]
    if total >= 5:
        if ht == 0 and tr == 0:
            lines.append(
                "**Assessment:** Concerning — all types in watch/weak bands"
            )
        elif ht + tr > total * 0.7:
            lines.append("**Assessment:** Compressed — too many in top bands")
        else:
            lines.append("**Assessment:** Healthy spread")
    return "\n".join(lines) + "\n"


def _divergence_section(recommendations: List[dict]) -> str:
    by_conf = sorted(
        recommendations,
        key=lambda r: r.get("confidence", 0.0),
        reverse=True,
    )
    conf_ranks = {
        r["recommendation_id"]: i + 1 for i, r in enumerate(by_conf)
    }
    by_trust = sorted(
        recommendations,
        key=lambda r: r.get("trust_score", 0.0),
        reverse=True,
    )
    trust_ranks = {
        r["recommendation_id"]: i + 1 for i, r in enumerate(by_trust)
    }
    deltas = []
    for rec in recommendations:
        rid = rec["recommendation_id"]
        c_rank = conf_ranks.get(rid)
        t_rank = trust_ranks.get(rid)
        if c_rank is None or t_rank is None:
            continue
        delta = abs(c_rank - t_rank)
        if delta >= 2:
            deltas.append({
                "title": rec.get("title", rid)[:40],
                "confidence_rank": c_rank,
                "trust_rank": t_rank,
                "delta": delta,
                "confidence": rec.get("confidence", 0.0),
                "trust_score": rec.get("trust_score", 0.0),
            })
    deltas.sort(key=lambda x: -x["delta"])
    if not deltas:
        return "*No meaningful divergences found*\n"
    lines = [
        "| Title | Conf Rank | Trust Rank | Delta | Conf | Trust |",
        "|---|---|---|---|---|---|",
    ]
    for d in deltas[:10]:
        lines.append(
            f"| {d['title']} | {d['confidence_rank']} | {d['trust_rank']} | "
            f"{d['delta']} | {d['confidence']:.2f} | {d['trust_score']:.2f} |"
        )
    return "\n".join(lines) + "\n"


def _drift_section(trust_types: List[dict]) -> str:
    signals = []
    for t in trust_types:
        trust = t.get("trust_score", 0.0)
        drift = t.get("drift_penalty", 0.0)
        if trust >= 0.60 and drift > 0.0:
            signals.append({
                "type": t.get("type", "")[:30],
                "trust": trust,
                "drift": drift,
                "severity": "critical" if drift > 0.20 else "warning",
            })
    signals.sort(key=lambda x: (-x["drift"], -x["trust"]))
    if not signals:
        return "*No drift signals detected*\n"
    lines = ["| Type | Trust | Drift | Severity |", "|---|---|---|---|"]
    for s in signals[:10]:
        lines.append(
            f"| {s['type']} | {s['trust']:.3f} | "
            f"{s['drift']:.3f} | {s['severity']} |"
        )
    return "\n".join(lines) + "\n"


def _raw_counts(
    trust_types: List[dict],
    recommendations: List[dict],
    effectiveness_types: List[dict],
) -> str:
    return (
        f"- Trust types: {len(trust_types)}\n"
        f"- Recommendations: {len(recommendations)}\n"
        f"- Effectiveness types: {len(effectiveness_types)}\n"
    )


def _assessment(
    trust_res: Dict[str, Any],
    conf_res: Dict[str, Any],
    drift_signals: List[dict],
) -> str:
    lines = []
    tr = trust_res.get("correlation")
    cr = conf_res.get("correlation")
    if tr is not None and tr >= 0.5:
        lines.append("- Trust → Resolution: **Good**")
    elif tr is not None and tr >= 0.3:
        lines.append("- Trust → Resolution: **Acceptable**")
    elif tr is not None:
        lines.append("- Trust → Resolution: **Poor** — extend burn-in")
    else:
        lines.append("- Trust → Resolution: **Insufficient data**")

    if cr is not None and cr >= 0.5:
        lines.append("- Confidence → Resolution: **Good**")
    elif cr is not None and cr >= 0.3:
        lines.append("- Confidence → Resolution: **Acceptable**")
    elif cr is not None:
        lines.append("- Confidence → Resolution: **Poor**")
    else:
        lines.append("- Confidence → Resolution: **Insufficient data**")

    critical = sum(1 for d in drift_signals if d.get("severity") == "critical")
    warnings = sum(1 for d in drift_signals if d.get("severity") == "warning")
    if critical:
        lines.append(
            f"- Drift: **{critical} critical, {warnings} warning** "
            f"— investigate"
        )
    elif warnings:
        lines.append(f"- Drift: **{warnings} warning** — monitor")
    else:
        lines.append("- Drift: **None detected**")

    lines.append("")
    lines.append("### Exit Criteria Check")
    lines.append("")
    lines.append("| Criterion | Target | Status |")
    lines.append("|---|---|---|")
    lines.append("| Trust Stability | < 0.10 week-over-week | ? |")
    lines.append("| Calibration Stability | < 0.05 week-over-week | ? |")
    lines.append("| Ranking Stability | < 20% band changes | ? |")
    _status = 'PASS' if tr is not None and tr >= 0.3 else 'PENDING'
    lines.append(
        "| Resolution Correlation | >= 0.3 (min), 0.5 (pref) | "
        f"{_status} |"
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Ω-7B.1 Trust Validation Report #1",
    )
    parser.add_argument("--api-url", default="http://127.0.0.1:8000")
    parser.add_argument("--api-key", default="dev-key-12345")
    parser.add_argument(
        "--output",
        default="reports/trust_validation_report.md",
        help="Output markdown file",
    )
    args = parser.parse_args()

    try:
        trust_data = _fetch(
            "/api/uar/recommendations/trust", args.api_url, args.api_key
        )
        recs_data = _fetch(
            "/api/uar/recommendations", args.api_url, args.api_key
        )
        eff_data = _fetch(
            "/api/uar/recommendations/effectiveness",
            args.api_url, args.api_key,
        )
    except requests.RequestException as e:
        print(f"API request failed: {e}", file=sys.stderr)
        return 1

    trust_types = trust_data.get("recommendation_types", [])
    recommendations = recs_data.get("recommendations", [])
    eff_types = eff_data.get("recommendation_types", [])

    # Compute correlations for assessment
    eff_map = {
        t["type"]: t.get("resolution_rate", 0.0)
        for t in eff_types if "type" in t
    }
    trust_scores = []
    conf_scores = []
    resolution_rates = []
    for t in trust_types:
        tn = t.get("type", "")
        if tn in eff_map:
            trust_scores.append(t.get("trust_score", 0.0))
            resolution_rates.append(eff_map[tn])
    for r in recommendations:
        rt = r.get("type", r.get("recommendation_type", ""))
        if rt in eff_map:
            conf_scores.append(r.get("confidence", 0.0))
    trust_res = _compute_correlation(trust_scores, resolution_rates)
    conf_res = _compute_correlation(conf_scores, resolution_rates)

    drift_signals = []
    for t in trust_types:
        trust = t.get("trust_score", 0.0)
        drift = t.get("drift_penalty", 0.0)
        if trust >= 0.60 and drift > 0.0:
            drift_signals.append({
                "type": t.get("type", ""),
                "trust": trust,
                "drift": drift,
                "severity": "critical" if drift > 0.20 else "warning",
            })

    # Build summary
    total_recs = len(recommendations)
    total_types = len(trust_types)
    summary = (
        f"This report analyzes {total_recs} recommendations "
        f"across {total_types} types. "
    )
    if trust_res.get("correlation") is not None:
        summary += (
            f"Trust → Resolution correlation is "
            f"{trust_res['correlation']:.3f} "
            f"({trust_res.get('assessment', 'unknown')}). "
        )
    if drift_signals:
        summary += f"{len(drift_signals)} drift signal(s) detected."
    else:
        summary += "No drift signals detected."

    report = REPORT_HEADER.format(
        date=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        status="PENDING" if trust_res.get("correlation") is None else "ACTIVE",
        summary=summary,
        trust_resolution=_trust_resolution_section(trust_types, eff_types),
        confidence_resolution=_confidence_resolution_section(
            recommendations, eff_types
        ),
        trust_distribution=_trust_distribution_section(trust_types),
        divergences=_divergence_section(recommendations),
        drift_events=_drift_section(trust_types),
        raw_counts=_raw_counts(trust_types, recommendations, eff_types),
        assessment=_assessment(trust_res, conf_res, drift_signals),
    )

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report)
    print(f"Report written to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
